### PR TITLE
I got bored

### PR DESCRIPTION
**Pull request by kckarnige**

### CODE REVIEW

**Comment by kckarnige** [comment]
Hold on, found some issues

**Comment by xhyrom** [comment]
okay

**Comment by kckarnige** [comment]
I had to fix something, I just got distracted throughout the day, and forgot about it

**Comment by kckarnige** [comment]
Sorry for taking 3 centuries =w="

**Comment by kckarnige** [comment]
I noticed you made the injector support PTB and Stable, I've disabled that a bit ago. This doesn't have that since that has been noted to be very unstable for Powercord since it's built with Canary in mind, and Discord Development uses Canary by default so that would be fine aswell.

**Comment by xhyrom** [comment]
Thank you, I'll check this when I'll be on computer

**Comment by kckarnige** [comment]
Banana

**Pull request merged**
